name: detect changes files

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changes.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: detect changes files
        id: changes
        run: |
          set -euo pipefail
          CHANGED_FILES=$(git diff --name-only ${{ github.sha }}^1 ${{ github.sha }} -- docs/)

          echo "Changed files: $CHANGED_FILES"

          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes in docs/"
            echo "files=[]" >> "$GITHUB_OUTPUT"
          else
            FILES_JSON=$(printf "%s\n" "$CHANGED_FILES" | jq -R -s -c 'split("\n") | map(select(length>0))')
            echo "files=$FILES_JSON" >> "$GITHUB_OUTPUT"
          fi

  echo-changes:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed-files != '[]'
    strategy:
      matrix:
        file: ${{ fromJson(needs.detect-changes.outputs.changed-files) }}
    steps:
      - name: echo changed file
        run: |
          echo "Changed file: ${{ matrix.file }}"
